### PR TITLE
Fossify website made with Astro js

### PR DESCRIPTION
**Pull request by ronniedroid**
@naveensingh The website is almost complete.

Missing things are: 

- The blogs page
- App info: right now I only have added a few and they need to be updated
- App screenshots: They all should have the same dimensions
- Updated hero image

Please let me know if I have to change anything.

### CODE REVIEW

**Comment by naveensingh** [comment]
Hi!
I'll be reviewing this later, is https://ronniedroid.github.io/fossifyorg.github.io the up-to-date place to go if I want to test things out?

Also, please resolve the conflicts :)

**Comment by ronniedroid** [comment]
Hey,

Take your time.

Yes it is 99% there (the app cards on mobile don't have the dynamic data) 

I will try that tomorrow.

**Comment by ronniedroid** [comment]
@naveensingh merge conflict fixed

BTW, the policies are in src/pages/policy.

**Comment by ronniedroid** [comment]
@naveensingh blog added, check it out please.

**Comment by ronniedroid** [comment]
Everything is tested and done. 

Only the app info and the translations need updating.

Some placeholder text needs to be replaced too.

**Comment by ronniedroid** [comment]
@naveensingh any updates on this one?

**Comment by naveensingh** [comment]
I still have not checked this yet. Been busier than usual lately.

**Comment by ronniedroid** [comment]
Will this ever get merged?

It's been months, and I would love it to be merged soon as I can add it to my portfolio.

**Comment by naveensingh** [comment]
I guess I'll skip the review and merge this now, although some elements like the donation page are still missing. We can address those later.

**Comment by naveensingh** [comment]
In case you've got some time for me: https://github.com/FossifyOrg/fossifyorg.github.io/actions/runs/10871348209

**Comment by naveensingh** [comment]
Actually, it's fixed now.

**Comment by ronniedroid** [comment]
> I guess I'll skip the review and merge this now, although some elements like the donation page are still missing. We can address those later.

Yes, some strings need updating, the logos need updating. App's data is incomplete I think. 

Let me know when you have reviewed it and tell me where it needs improvements.

Also, would be nice of the first blog post was from you, announcing the website itself and maybe talking about the project's progress so far :-)

**Pull request merged**
